export const toolsList = [
	{
		id: 'builds',
		icon: 'lucide:package',
		title: 'landing.tools.tool_list.builds.title',
		desc: 'landing.tools.tool_list.builds.desc',
		link: '/calcs/builds',
	},
	{
		id: 'buildsLite',
		icon: 'lucide:panel-top',
		title: 'landing.tools.tool_list.builds_lite.title',
		desc: 'landing.tools.tool_list.builds_lite.desc',
		link: '/calcs/builds/lite',
	},
	{
		id: 'buy',
		icon: 'lucide:shopping-basket',
		title: 'landing.tools.tool_list.buy.title',
		desc: 'landing.tools.tool_list.buy.desc',
		link: '/calcs/buy',
	},
	{
		id: 'ttk',
		icon: 'lucide:timer-reset',
		title: 'landing.tools.tool_list.ttk.title',
		desc: 'landing.tools.tool_list.ttk.desc',
		link: '/calcs/ttk',
	},
	{
		id: 'arsenal',
		icon: 'lucide:table-properties',
		title: 'landing.tools.tool_list.arsenal.title',
		desc: 'landing.tools.tool_list.arsenal.desc',
		link: '/calcs/arsenal',
	},
	{
		id: 'bp',
		icon: 'lucide:ticket',
		title: 'landing.tools.tool_list.bp.title',
		desc: 'landing.tools.tool_list.bp.desc',
		link: '/calcs/bp',
	},
	{
		id: 'player_search',
		icon: 'lucide:user-round-search',
		title: 'landing.tools.tool_list.player_search.title',
		desc: 'landing.tools.tool_list.player_search.desc',
		link: '/player',
	},
]
