export interface Game {
	name: string
	slug: string
	yawdeg: number | null
	yawrad: number | null
}

export const games: Game[] = [
	{ name: '1v1.LOL', slug: '1v1-lol', yawdeg: 0.006052164616, yawrad: null },
	{
		name: '7 Days to Die',
		slug: '7-days-to-die',
		yawdeg: 0.25,
		yawrad: null,
	},
	{ name: 'Aim Gods', slug: 'aim-gods', yawdeg: 0.0023331, yawrad: null },
	{ name: 'Aim Lab', slug: 'aim-lab', yawdeg: 0.05, yawrad: null },
	{ name: 'STALCRAFT', slug: 'stalcraft', yawdeg: 0.0066, yawrad: null },
	{ name: 'Aimtastic', slug: 'aimtastic', yawdeg: 0.022, yawrad: null },
	{ name: 'Apex Legends', slug: 'apex-legends', yawdeg: 0.022, yawrad: null },
	{ name: 'Arma 3', slug: 'arma-3', yawdeg: null, yawrad: null },
	{
		name: 'Battalion 1944',
		slug: 'battalion-1944',
		yawdeg: 0.0175,
		yawrad: null,
	},
	{
		name: 'BattleBit Remastered',
		slug: 'battle-bit',
		yawdeg: 5e-4,
		yawrad: null,
	},
	{
		name: 'Battlefield V/1/Hardline',
		slug: 'battlefield-v',
		yawdeg: null,
		yawrad: 0.04,
	},
	{
		name: 'Black Squad',
		slug: 'black-squad',
		yawdeg: 0.005493164063,
		yawrad: null,
	},
	{ name: 'Bloodhunt', slug: 'bloodhunt', yawdeg: 0.066727, yawrad: null },
	{
		name: 'Borderlands 1/2',
		slug: 'borderlands',
		yawdeg: 0.005493164063,
		yawrad: null,
	},
	{
		name: 'Borderlands 3',
		slug: 'borderlands-3',
		yawdeg: 0.007003891051,
		yawrad: null,
	},
	{
		name: 'Call of Duty: Black Ops 4',
		slug: 'call-of-duty-black-ops-4',
		yawdeg: 0.006605686395,
		yawrad: null,
	},
	{
		name: 'Call of Duty: Black Ops 6',
		slug: 'call-of-duty-black-ops-6',
		yawdeg: 0.0066,
		yawrad: null,
	},
	{
		name: 'Call of Duty: Black Ops Cold War',
		slug: 'call-of-duty-black-ops-cold-war',
		yawdeg: 0.0066,
		yawrad: null,
	},
	{
		name: 'Call of Duty: Modern Warfare',
		slug: 'call-of-duty',
		yawdeg: 0.0066,
		yawrad: null,
	},
	{
		name: 'Call of Duty: Warzone',
		slug: 'call-of-duty-warzone',
		yawdeg: 0.0066,
		yawrad: null,
	},
	{
		name: 'Call of Duty: WWII',
		slug: 'call-of-duty-wwii',
		yawdeg: 0.022,
		yawrad: null,
	},
	{
		name: 'Creative Destruction',
		slug: 'creative-destruction',
		yawdeg: 390625e-9,
		yawrad: null,
	},
	{ name: 'CS 1.6', slug: 'cs-16', yawdeg: 0.022, yawrad: null },
	{ name: 'CS2', slug: 'cs-2', yawdeg: 0.022, yawrad: null },
	{ name: 'CS:GO', slug: 'cs-go', yawdeg: 0.022, yawrad: null },
	{ name: 'Cyberpunk 2077', slug: 'cyberpunk', yawdeg: 0.01, yawrad: null },
	{
		name: 'Darwin Project',
		slug: 'darwin-project',
		yawdeg: 0.00174504843,
		yawrad: null,
	},
	{ name: 'DayZ', slug: 'dayz', yawdeg: 0.178571428571, yawrad: null },
	{ name: 'Deadlock', slug: 'deadlock', yawdeg: 0.044, yawrad: null },
	{
		name: 'Deep Rock Galactic',
		slug: 'deep-rock-galactic',
		yawdeg: 133667006e-12,
		yawrad: null,
	},
	{ name: 'Destiny 2', slug: 'destiny-2', yawdeg: 0.0066, yawrad: null },
	{ name: 'Doom Eternal', slug: 'doom-eternal', yawdeg: 0.022, yawrad: null },
	{
		name: 'Dying Light',
		slug: 'dying-light',
		yawdeg: 0.008333333333,
		yawrad: null,
	},
	{
		name: 'Escape from Tarkov',
		slug: 'escape-from-tarkov',
		yawdeg: 0.125,
		yawrad: null,
	},
	{ name: 'Fallout 4', slug: 'fallout-4', yawdeg: 3.78, yawrad: null },
	{ name: 'Far Cry 3', slug: 'far-cry-3', yawdeg: 0.18, yawrad: null },
	{ name: 'Far Cry 4', slug: 'far-cry-4', yawdeg: 0.036, yawrad: null },
	{ name: 'Far Cry 5', slug: 'far-cry', yawdeg: 0.022, yawrad: null },
	{
		name: 'Far Cry Primal',
		slug: 'far-cry-primal',
		yawdeg: 0.053820025834,
		yawrad: null,
	},
	{ name: 'Fortnite', slug: 'fortnite', yawdeg: 0.005555, yawrad: null },
	{ name: "Garry's Mod", slug: 'garrys-mod', yawdeg: 0.022, yawrad: null },
	{ name: 'Gears 5', slug: 'gears', yawdeg: 0.012438884908, yawrad: null },
	{ name: 'Halo', slug: 'halo', yawdeg: 0.022222222222, yawrad: null },
	{
		name: 'Halo Infinite',
		slug: 'halo-infinite',
		yawdeg: 0.0225,
		yawrad: null,
	},
	{
		name: 'Heroes & Generals',
		slug: 'heroes-generals',
		yawdeg: 0.151260504202,
		yawrad: null,
	},
	{
		name: 'Hunt: Showdown',
		slug: 'hunt-showdown',
		yawdeg: null,
		yawrad: 75e-5,
	},
	{ name: 'Hyperscape', slug: 'hyperscape', yawdeg: null, yawrad: 1e-4 },
	{ name: 'Insurgency', slug: 'insurgency', yawdeg: 0.022, yawrad: null },
	{
		name: 'Insurgency: Sandstorm',
		slug: 'insurgency-sandstorm',
		yawdeg: 0.14,
		yawrad: null,
	},
	{ name: 'Ironsight', slug: 'ironsight', yawdeg: 0.01, yawrad: null },
	{ name: 'Krunker', slug: 'krunker', yawdeg: 0.137509549274, yawrad: null },
	{
		name: 'Line of Sight',
		slug: 'line-of-sight',
		yawdeg: 0.005493164063,
		yawrad: null,
	},
	{
		name: 'Marvel Rivals',
		slug: 'marvel-rivals',
		yawdeg: 0.0175,
		yawrad: null,
	},
	{
		name: 'Minecraft Java Edition',
		slug: 'minecraft',
		yawdeg: null,
		yawrad: null,
	},
	{ name: 'Overwatch', slug: 'overwatch', yawdeg: 0.0066, yawrad: null },
	{ name: 'Overwatch 2', slug: 'overwatch-2', yawdeg: 0.0066, yawrad: null },
	{
		name: 'Paladins',
		slug: 'paladins',
		yawdeg: 0.009155273438,
		yawrad: null,
	},
	{ name: 'Payday 2', slug: 'payday-2', yawdeg: 0.15, yawrad: null },
	{ name: 'Payday 3', slug: 'payday-3', yawdeg: 0.07, yawrad: null },
	{
		name: 'PUBG',
		slug: 'player-unknown-battlegrounds',
		yawdeg: 2.222,
		yawrad: null,
	},
	{ name: 'Quake Live', slug: 'quake-live', yawdeg: 0.022, yawrad: null },
	{
		name: 'Realm Royale',
		slug: 'realm-royale',
		yawdeg: 0.009155273438,
		yawrad: null,
	},
	{
		name: 'Ring of Elysium',
		slug: 'ring-of-elysium',
		yawdeg: 2.222,
		yawrad: null,
	},
	{ name: 'Roblox', slug: 'roblox', yawdeg: 0.401785714286, yawrad: null },
	{
		name: 'Rogue Company',
		slug: 'rogue-company',
		yawdeg: 0.0227289,
		yawrad: null,
	},
	{ name: 'Rust', slug: 'rust', yawdeg: 0.1125, yawrad: null },
	{
		name: 'Spectre Divide',
		slug: 'spectre-divide',
		yawdeg: 0.0715206,
		yawrad: null,
	},
	{ name: 'Splitgate', slug: 'splitgate', yawdeg: 0.93740625, yawrad: null },
	{ name: 'Squad', slug: 'squad', yawdeg: 0.1749825, yawrad: null },
	{
		name: 'Team Fortress 2',
		slug: 'team-fortress-2',
		yawdeg: 0.022,
		yawrad: null,
	},
	{ name: 'THE FINALS', slug: 'the-finals', yawdeg: 0.1, yawrad: null },
	{ name: 'Titanfall 2', slug: 'titanfall-2', yawdeg: 0.022, yawrad: null },
	{
		name: "Tom Clancy's Rainbow 6: Siege",
		slug: 'rainbow-6-siege',
		yawdeg: null,
		yawrad: 1e-4,
	},
	{
		name: "Tom Clancy's The Division 2",
		slug: 'the-division-2',
		yawdeg: 0.0044691,
		yawrad: null,
	},
	{ name: 'Unturned', slug: 'unturned', yawdeg: 0.1, yawrad: null },
	{ name: 'Valheim', slug: 'valheim', yawdeg: 0.05, yawrad: null },
	{ name: 'Valorant', slug: 'valorant', yawdeg: 0.07, yawrad: null },
	{ name: 'Warface', slug: 'warface', yawdeg: 0.00333000333, yawrad: null },
	{
		name: 'Warframe',
		slug: 'warframe',
		yawdeg: 0.007566132006,
		yawrad: null,
	},
	{ name: 'XDefiant', slug: 'xdefiant', yawdeg: 0.00170729845, yawrad: null },
	{ name: 'Xonotic', slug: 'xonotic', yawdeg: 0.022, yawrad: null },
	{ name: 'Zula', slug: 'zula', yawdeg: 0.12012012012, yawrad: null },
]
